### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by LiftedRocket01** [faroukbmiled/BOIIIWD#35]
Failed to execute script 'boiiiwd' due to unhandled exception: [Errno 13] (not a typo) Permission denied: 'config.ini'

Traceback (most recent call last):
  File "boiiiwd.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "src\shared_vars.py", line 3, in <module>
  File "src\main.py", line 197, in __init__
  File "src\main.py", line 461, in load_configs
  File "src\helpers.py", line 231, in create_default_config
PermissionError: [Errno 13] Permission denied: 'config.ini'

deleting config file works but is annoying to relocate steamcmd and do personalization each time.

**Comment by LiftedRocket01** [comment]
Seems like it only happens when you launch boiiiwd from windows drawer...

**Comment by faroukbmiled** [comment]
> Seems like it only happens when you launch boiiiwd from windows drawer...

Will look into this!
